{% set name = "envs" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d8435c6985d1cdd68299e04c58e2bdb8ae6cf66b2596a8079e6f9a93f2a0398

build:
  noarch: python
  number: 0
  entry_points:
    - envs=envs.cli:envs
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - click
    - jinja2
    - terminaltables

test:
  requires:
    - click
    - jinja2
    - terminaltables
  imports:
    - envs
  commands:
    - envs --help

about:
  home: https://github.com/bjinwright/envs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy access of environment variables from Python with support for strings, booleans, list, tuples, and dicts.
  dev_url: https://github.com/bjinwright/envs

extra:
  recipe-maintainers:
    - mxr-conda
    - benhuff
    - oblute
    - rluria14
